// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utprodzezzwiixofsgmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cHJvZHplenp3aWl4b2ZzZ21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NjM0MDQsImV4cCI6MjA3NTQzOTQwNH0.NbNsltj2QqEnhCxrqdYtdtzld-c26UqmLkcVt2UJmXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});